export const GET_TODO_REQUEST="GET_TODO_REQUEST"
export const GET_TODO_SUCCESS="GET_TODO_SUCCESS"
export const GET_TODO_FAILURE="GET_TODO_FAILURE"


export const POST_TODO_REQUEST="POST_TODO_REQUEST"
export const POST_TODO_SUCCESS="POST_TODO_SUCCESS"
export const POST_TODO_FAILURE="POST_TODO_FAILURE"

export const PATCH_TODO_REQUEST="PATCH_TODO_REQUEST"
export const PATCH_TODO_SUCCESS="PATCH_TODO_SUCCESS"
export const PATCH_TODO_FAILURE="PATCH_TODO_FAILURE"


export const DELETE_TODO_REQUEST="DELETE_TODO_REQUEST"
export const DELETE_TODO_SUCCESS="DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAILURE="DELETE_TODO_FAILURE"