export const GET_LOGIN_REQUEST="GET_LOGIN_REQUEST"
export const GET_LOGIN_SUCCESS="GET_LOGIN_SUCCESS"
export const GET_LOGIN_FAILURE="GET_LOGIN_FAILURE"

export const POST_REGISTER_REEQUEST="POST_REGISTER_REEQUEST"
export const POST_REGISTER_SUCCESS="POST_REGISTER_SUCCESS"
export const POST_REGISTER_FAILURE="POST_REGISTER_FAILURE"

export const USER_LOGOUT="USER_LOGOUT"